services:
  - redis-server
  - memcache
  
env:
  global:
    - REPO="webignition/worker.simplytestable.com"
    - CI_HOME=`pwd`/$REPO  

language: php
php:
  #- 5.3
  - 5.4
  #- 5.5

before_script:
  # General prep
  - sudo chmod +x ./travis/*.sh
  - ./travis/prep.sh
  
  # Install the W3C HTML validator
  #- sudo ./travis/install-html-validator.sh
  
  # Install nodejs and node-jslint
  #- sudo ./travis/install-node-jslint.sh  

  # Install the W3C CSS validator  
  - sudo ./travis/install-css-validator.sh  
  
  # Install memcache extension and verify installation
  #- wget http://pecl.php.net/get/memcache-2.2.7.tgz
  #- tar -zxf memcache-2.2.7.tgz
  #- sh -c "cd memcache-2.2.7 && phpize && ./configure && make --quiet && sudo make --quiet install"
  #- echo "extension=memcache.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s/.*:\s*//"`  
  #- php -r 'new \Memcache;'
  
  # Install the W3C CSS validator
  #- sudo apt-get update
  #- sudo apt-get install ant cvs openjdk-7-jdk
  #- sudo mkdir /usr/share/css-validator
  #- cd /usr/share/css-validator
  #- sudo CVSROOT=:pserver:anonymous:anonymous@dev.w3.org:/sources/public cvs -q checkout 2002/css-validator
  #- cd 2002/css-validator/
  #- sudo sed -i 's/http:\/\/about.validator.nu\/htmlparser\/htmlparser-1.3.1.zip/ftp:\/\/ftp.linux.org.tr\/gentoo\/distfiles\/htmlparser-1.3.1.zip/g' build.xml
  #- sudo ant -q jar
  #- cd $CI_HOME
  
  # Install composer for dependency management
  #- wget http://getcomposer.org/composer.phar 
  
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  #- "mkdir -p ~/.composer"
  #- cp .travis.composer.config.json ~/.composer/config.json  
  
script:
  - echo "Hello World!"

  
#notifications:
#  irc:
#    - "irc.freenode.org#simplytestable"
    
