services:
  - redis-server
  - memcache
  
env:
  global:
    - REPO="webignition/worker.simplytestable.com"
    - CI_HOME=`pwd`/$REPO  

language: php
php:
  #- 5.3
  - 5.4
  #- 5.5

before_script:
  # General prep
  - sudo chmod +x ./travis/*.sh
  - ./travis/prep.sh
  
  - which php
  - "php -v"
  
  # Install the W3C HTML validator
  #- sudo ./travis/install-html-validator.sh
  
  # Install nodejs and node-jslint
  #- sudo ./travis/install-node-jslint.sh  

  # Install the W3C CSS validator  
  #- sudo ./travis/install-css-validator.sh  
  
  # Install PHP extensions
  #- sudo ./travis/install-php-extensions.sh  
  
  # Install composer for dependency management
  #- wget http://getcomposer.org/composer.phar 
  
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  #- "mkdir -p ~/.composer"
  #- cp .travis.composer.config.json ~/.composer/config.json  
  
script:
  - echo "Hello World!"
  - which php
  - "php -v"

  
#notifications:
#  irc:
#    - "irc.freenode.org#simplytestable"
    
