services:
  - redis-server
  - memcache
  
env:
  global:
    - REPO="webignition/simplytestable-travis-integration"
    - CI_HOME=`pwd`/$REPO

language: php
php:
  #- 5.3
  - 5.4
  #- 5.5

before_script:
  # Disable strict host checking for github.com
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  
  # General prep
  - sudo chmod -R +x ./travis/*.sh
  - sudo chmod -R +x travis/install/3rdparty/*.sh
  - sudo chmod -R +x travis/install/simplytestable/*.sh
  - sudo chmod -R +x travis/install/simplytestable/core-app/*.sh
  - ./travis/prep.sh
  
  # Install the W3C HTML validator
  #- sudo ./travis/install/3rdparty/html-validator.sh
  
  # Install nodejs and node-jslint
  #- sudo ./travis/install/3rdparty/node-jslint.sh  

  # Install the W3C CSS validator  
  #- sudo ./travis/install/3rdparty/css-validator.sh  
  
  # Install PHP extensions
  #- sudo ./travis/install/3rdparty/php-extensions.sh  
  
  # Install nginx and php-fpm
  - sudo ./travis/install/3rdparty/nginx-php-fpm.sh
  
  # Install composer for dependency management
  - cd $CI_HOME
  - wget http://getcomposer.org/composer.phar 
  - chmod +x composer.phar
  
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json  
  
  # Prep for installing SimplyTestable applications
  - ./travis/install/simplytestable/prep.sh
  
  # Install core app, configure nginx and hosts entry
  - ./travis/install/simplytestable/core-app/install.sh
  - ./travis/install/simplytestable/core-app/configure-nginx.sh
  - ./travis/install/simplytestable/core-app/set-hosts-entry.sh

  #- sudo service nginx restart
  - "curl -v http://app.integration.simplytestable.com/"
  - ls -la /var/log/nginx  
  - ls -la /home/travis/simplytestable/www/app.integration.simplytestable.com/
  - ls -la /home/travis/simplytestable/www/app.integration.simplytestable.com/app
  - ls -la /home/travis/simplytestable/www/app.integration.simplytestable.com/app/cache
  - ls -la /home/travis/simplytestable/www/app.integration.simplytestable.com/app/cache/prod
  - ls -la /home/travis/simplytestable/www/app.integration.simplytestable.com/app/logs
  - cat /var/log/nginx/app.integration.simplytestable.com.access.log
  - tail /home/travis/simplytestable/www/app.integration.simplytestable.com/app/logs/prod.log -n30
  - sudo cat /var/log/php5-fpm.log
  - php -r "phpinfo();" | grep pdo
  - cat /home/travis/simplytestable/www/app.integration.simplytestable.com/app/config/parameters.yml
  - sudo find / -name 'php.ini'
  
script:
  - echo "Hello World!"
  
#notifications:
#  irc:
#    - "irc.freenode.org#simplytestable"
    
